version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: MauUser
      POSTGRES_DB: task_master_DB
    container_name: task_master_container_DB
    